# Generated by Django 5.2.10 on 2026-01-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_customer_billing_address_customer_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
