# Generated by Django 5.2.10 on 2026-01-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_customer_billing_address_customer_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50)),
                ('last_calibration_date', models.DateField()),
                ('calibration_interval_days', models.IntegerField(default=365)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('FAI', 'First Article Inspection'), ('IN_PROCESS', 'In-Process'), ('FINAL', 'Final Inspection')], default='FAI', max_length=20)),
                ('part_number', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('fai_report_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('inspector_name', models.CharField(blank=True, max_length=100)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='PENDING', max_length=10)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='production.job')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_number', models.IntegerField(help_text='The balloon number from the drawing')),
                ('description', models.CharField(help_text='e.g., Hole Diameter', max_length=200)),
                ('requirement', models.CharField(help_text='e.g., 0.500 +/- 0.005', max_length=100)),
                ('nominal_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('upper_tolerance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lower_tolerance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pass_fail', models.BooleanField(default=False)),
                ('equipment_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.equipment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='quality.inspectionreport')),
            ],
        ),
    ]
